Keep MODEL_DIR consistent in README
magenta/magenta pull request #2019
Opened 2022-09-22 14:53 UTC by mgogag

After having a messy result, I realised the README used the incorrect variable name.

2022-09-28 16:57 UTC, cghawthorne requested changes
Thanks for the fix! Can you update the usage in the Inference section too?

2022-10-02 10:46 UTC, mgogag commented
I'm new to the github thing so hopefully now it should be done

2022-10-03 18:48 UTC, cghawthorne approved these changes

2022-10-03 18:50 UTC, cghawthorne commented
Ah, looks like you still need to sign the CLA. Once you do that, we can merge the change. Thanks!

2022-10-04 06:42 UTC, mgogag commented
Okay I've signed the CLA

2022-10-04 17:42 UTC, merged